server:
  port: 8091

spring:
  application:
    name: wf-iot-api-enterprise
  cloud:
    bus:
      enabled: true
    stream:
      kafka:
        binder:
          autoCreateTopics: true
          autoAddPartitions: false
          #brokers: outer.warpfuture.com:9092
          brokers: 10.10.2.21:9092
          minPartitionCount: 1
      bindings:
        output:
          destination: wf_iot_data
          group: wf-iot-data1
          consumer:
            concurrency: 3
            partitioned: false
        input:
          destination: wf_iot_data
          contentType: text/plain
          producer:
            partitionCount: 1
  output:
    ansi:
      enabled: detect

  data:
    cassandra:
          keyspace-name: wf_iot
          port: 9042
          contactpoints: 10.10.2.21

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include:
          - "health"
          - "info"
          - "refresh"
  endpoint:
    health:
      enabled: true
      cache:
        time-to-live: 10s
      show-details: always
  server:
    port: 7091
