spring:
  data:
    mongodb:
      database: iot
      port: 27017
      #host: 127.0.0.1
      host: 10.10.2.21
  redis:
    port: 6379
    host: 10.10.2.21
    timeout: 5000s
#
    cassandra:
        keyspace-name: wf_iot
        port: 9042
        contactpoints: 10.10.2.21

server:
  port: 8082


